const express=require('express')
const router=express.Router()
const authorisation=require('../middlewares/authorisation')
const {createProducts,displayProducts,myProducts, getProductDetails, addToCart,getCartItems,removeCartItems,deleteProduct,updateProduct}=require('../controllers/productsController')
router.post('/create',authorisation,createProducts)
router.get('/display',displayProducts)
router.get('/details/:productID',getProductDetails)
router.get('/myProducts',authorisation,myProducts)
router.patch('/addToCart',authorisation,addToCart)
router.get('/cart',authorisation,getCartItems)
router.patch('/removeFromCart',authorisation,removeCartItems)
router.delete('/delete/:productID',authorisation,deleteProduct)
router.patch('/update/:productID',authorisation,updateProduct)
module.exports=router