const express=require('express')
const router=express.Router()
const cors=require('cors')
router.use(cors())
const {updateUserData,createOrder,getUserOrders}=require('../controllers/userController')
const Authorization=require('../middlewares/authorisation')
router.patch('/updateUser',Authorization,updateUserData)
router.post('/createOrder',Authorization,createOrder)
router.get('/orders',Authorization,getUserOrders)
module.exports=router